version: '3.8'
services:
  nifi:
    image: apache/nifi:latest # Or a specific version like apache/nifi:1.24.0
    ports:
      - "8443:8443" # NiFi UI port
    environment:
      NIFI_WEB_HTTP_PORT: 8080
    volumes:
      - nifi_data:/opt/nifi/nifi-current/data # Persistent NiFi data

      - ./nifi_jdbc_drivers/postgresql-42.7.6.jar:/opt/nifi/nifi-current/lib/postgresql-42.7.6.jar
    networks:
      - nifi_network

  postgres:
    image: postgres:latest # Or a specific version like postgres:16
    ports:
      - "5432:5432" # PostgreSQL default port
    environment:
      POSTGRES_DB: nifidb
      POSTGRES_USER: nifiuser
      POSTGRES_PASSWORD: nifipassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nifi_network

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080" # Adminer UI available at localhost:8080
    depends_on:
      - postgres
    networks:
      - nifi_network

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"  # S3 API
      - "9001:9001"  # MinIO console
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - minio_data:/data
    networks:
      - nifi_network
volumes:
  nifi_data:
  postgres_data:
  pgadmin_data:
  minio_data:

networks:
  nifi_network:
    driver: bridge