version: '3.8'

services:
  nifi:
    image: apache/nifi:latest
    ports:
      - "8081:8080"            # NiFi UI on http://localhost:8081
    environment:
      NIFI_WEB_HTTP_PORT: 8080 # run NiFi in HTTP (dev)
    volumes:
      - nifi_data:/opt/nifi/nifi-current/data
      - ./nifi_jdbc_drivers/postgresql-42.7.6.jar:/opt/nifi/nifi-current/lib/postgresql-42.7.6.jar
    networks: [nifi_network]
    depends_on:
      - minio

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: nifidb
      POSTGRES_USER: nifiuser
      POSTGRES_PASSWORD: nifipassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks: [nifi_network]

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"            # http://localhost:8080
    depends_on: [postgres]
    networks: [nifi_network]

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"            # S3 API
      - "9001:9001"            # MinIO console: http://localhost:9001
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - minio_data:/data
    networks: [nifi_network]

  minio-init:
    image: minio/mc:latest
    depends_on: [minio]
    entrypoint: >
      /bin/sh -c "
      mc alias set local http://minio:9000 minio minio123 &&
      mc mb -p local/iceberg || true &&
      # OPTIONAL: create a least-privilege user just for Iceberg writers
      mc admin user add local iceberg_user iceberg_secret || true &&
      mc admin policy create local iceberg_rw /tmp/iceberg-rw.json || true &&
      mc admin policy attach local iceberg_rw --user iceberg_user || true &&
      sleep 2
      "
    volumes:
      - ./minio-policies:/tmp
    networks: [nifi_network]
    restart: "no"

volumes:
  nifi_data:
  postgres_data:
  minio_data:

networks:
  nifi_network:
    driver: bridge
